In [1]:
# Purpose of this all is to get more comfy with numpy
# plus I don't really understand how numpy maps to matrices and tensors and how the axises work
# or broadcasting... much to do!

import numpy as np

In [5]:
# Matrix shapes


A = np.asarray([ [1, 2] , [3, 4] , [5, 6] ])

A.shape


(3, 2)

In [6]:
# A's shape is (3, 2) because it's an array of 3 elements, each element is an array of 2 elements

# So logically this array's shape should be (1, 2, 3)
np.asarray([ [[1,2,3],[4,5,6]] ]).shape


(1, 2, 3)

In [9]:
# Matrix multiply

A = np.asarray([ [1, 2] , [3, 4] , [5, 6] ])

# A's shape is (3, 2) so you would think it's a linear map fro R^3 to R^2 ?
v = np.asarray([1, 2, 3])
np.dot(A, v)


ValueError: shapes (3,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)

In [12]:
# Doesn't align, much sad
# It expected something in R^2

A = np.asarray([ [1, 2] , [3, 4] , [5, 6] ])

print(np.dot(A, np.asarray([1, 0])))
print(np.dot(A, np.asarray([0, 1])))

# This means that when we do np.asarray, it's reading row vectors
# And the shape is (rows, cols)


[1 3 5]
[2 4 6]


In [55]:
# Matrix matrix multiply

# Let's multiply something from R^1 => R^2 and something from R^2 => R^3
# Expect something from R^1 => R^3
# Multiply a (2, 1) by a (3, 2) to get a (3, 1)

# Writing things out in row for is so confusing omg, I'm going to write it out in column form and transpose

A = np.asarray([[1, 2]]).T
B = np.asarray([[3, 4, 5], [6, 7, 8]]).T

print(A.shape)
print(B.shape)
print(np.matmul(A, B).shape)


(2, 1)
(3, 2)


ValueError: shapes (2,1) and (3,2) not aligned: 1 (dim 1) != 3 (dim 0)

In [56]:
# Rookie mistake, to compose A with B, it's B(A(x))

print(np.matmul(B, A).shape)

(3, 1)


In [58]:
# Tensor multiply

# Let's say I had an array of matrices

# Represents 2 images of 3 rows x 4 cols pixels
A = np.zeros((2, 3, 4)) 

# An there's some matrix I want to compose with each of those images
B = np.zeros( (6, 3))

print(A.shape)
print(B.shape)
print(np.matmul(B, A).shape)

# I think it broadcasts B to some higher dimensional thing in the process


(2, 3, 4)
(6, 3)
(2, 6, 4)


In [68]:
# Lets say I had an array of matrices again

# But this time, my transformation takes vectors and spits out matrices

A = np.zeros((2, 3, 4))

B = np.zeros((6, 5, 3))

# This would take the 4 columns of A and turn each into a 6 x 5 matrix

# I could reshape B and then do a matmul and then reshape again..
print(np.matmul(B.reshape((6 * 5, 3)), A).reshape((2, 6, 5, 4)).shape)

# Honestly this is probably a ton easier than figuring out tensordots
# Reshape things into matrices, matmul, then reshape back into whatever you intended in the beginning
# Starting from general axises to more granular axises
# (like in this case axis 0 is the set of images and axes 1 and 2 are the image itself)


(2, 6, 5, 4)


In [81]:
# So how do these axes work??

A = np.zeros((2, 3, 4, 5, 6))
# Add everything
print(A.sum())

print(A.sum(axis=(0)).shape)
print(A.sum(axis=(1)).shape)
print(A.sum(axis=(2)).shape)
print(A.sum(axis=(3)).shape)

print(A.sum(axis=(0, 1)).shape)
print(A.sum(axis=(0, 4)).shape)
print(A.sum(axis=(3, 1)).shape)


0.0
(3, 4, 5, 6)
(2, 4, 5, 6)
(2, 3, 5, 6)
(2, 3, 4, 6)
(4, 5, 6)
(3, 4, 5)
(2, 4, 6)


In [82]:
# Summing over specific axises deletes those axises

# So if I had a matrix and I sum over axis 0 (the rows)
# I actually get back sum of each column

A = np.asarray([[1, 2], [3, 4]])

A.sum(axis=0)


array([4, 6])